services:
  frontend:
    build:
      context: .
    image: portfolio_frontend
    container_name: portfolio_frontend
    ports:
      - "3000:3000"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
