services:
  frontend:
    build:
      context: .
      args:
        RESEND_API_KEY: "re_DJbRAiUp_5UrD96CMkuWhYqR26GMWGpSC"
    image: portfolio_frontend
    container_name: portfolio_frontend
    ports:
      - "4000:3000"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
