services:
  frontend:
    build:
      context: .
      args:
        RESEND_API_KEY: "re_DJbRAiUp_5UrD96CMkuWhYqR26GMWGpSC"
    image: hungthai_portfolio_frontend
    container_name: hungthai_portfolio_frontend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
